KFAX-23 : Expose parameters which required to determine file upload file size
2600hz/kazoo-proper pull request #147
Opened 2023-04-25 15:54 UTC by wdhammika

Previously, Support did not know what the monster UI should be updated to, Currently, we have 3 different answers, comm.land states 15mb, the documentation states 3mb, and eFax in Kazoo report 20 MB. We are trying to track down the correct size

Two configuration parameters have been identified which determine file size.

```
crossbar => max_upload_size
fax => smtp_max_msg_size
```
Therefore `v2/accounts/{ACCOUNT_ID}/configs` has been configured to return parameters that UI needed to determine the file size and others. So UI can access those values through API.

Original pull request: https://github.com/2600hz/kazoo-crossbar/pull/468
This Properly test is for testing the above scenario.

2023-04-25 17:54 UTC, harenson requested changes
Please, within this PR's _description_, link the PRs' these tests "belongs" to.

2023-04-25 17:54 UTC, harenson commented on src/api/pqc_cb_configs.erl
> +-export([
Not need for the extra new line.

2023-04-25 17:54 UTC, harenson commented on src/api/pqc_cb_configs.erl
> +default_configs(API) ->
Please, rename this function. Call it _fetch_ as all the other pqc modules do.

2023-04-25 17:54 UTC, harenson commented on src/seq/seq_configs.erl
> +    validate_key(kz_json:get_value(<<"id">>, Data)),
I don't think you need an extra function to test the id. Something like the following would do the trick as well:
```erlang
<<"configs_default">> = kz_json:get_binary_value(<<"id">>, Data)
```

Also, the way you are testing it, the test will not fail, even when an invalid _id_ is provided, it will just log "UNDEFINED KEY undefined".

2023-04-25 17:54 UTC, harenson commented on src/seq/seq_configs.erl
> +
Checks for `smtp_max_msg_size` and `max_upload_size` fields are missing. Something like:
```erlang
20 = kz_json:get_integer_value(<<"smtp_max_msg_size">>, Data),
20 = kz_json:get_integer_value(<<"max_upload_size">>, Data),
```

2023-05-03 16:17 UTC, wdhammika commented on src/api/pqc_cb_configs.erl
> +-export([
Fixed

2023-05-03 16:17 UTC, wdhammika commented on src/api/pqc_cb_configs.erl
> +default_configs(API) ->
fixed

2023-05-03 16:18 UTC, wdhammika commented on src/seq/seq_configs.erl
> +    validate_key(kz_json:get_value(<<"id">>, Data)),
fixed

2023-05-03 16:18 UTC, wdhammika commented on src/seq/seq_configs.erl
> +
fixed

2023-05-09 21:47 UTC, merged