KCRO-190: Additional APIs to consume pvt_chat.getstream in user doc
2600hz/kazoo-proper pull request #172
Opened 2023-07-25 15:19 UTC by Navoda626

Adding tests for the following APIs

**GET accounts/{ACCOUNT_ID}/users/getstream** <-- list all user documents with pvt_chat.getstream.enabled == true

**GET accounts/{ACCOUNT_ID}/users/{USER_ID}/getstream** <-- get the getstream object of a specific user

**PUT accounts/{ACCOUNT_ID}/users/{USER_ID}/getstream** <-- sets pvt_chat.getstream.enabled = true and set any object in json data into getstream object for the USER_ID and return the pvt_chat.getsream object

**PATCH accounts/{ACCOUNT_ID}/users/{USER_ID}/getstream** <-- merge the json data with pvt_chat.getstream (overwriting existing parameters including the value of enabled ) and return the pvt_chat.getsream object

**DELETE accounts/{ACCOUNT_ID}/users/{USER_ID}/getstream** <-- removes the property pvt_chat.getstream.enabled for the USER_ID and return the deleted pvt_chat.getsream object

2023-07-26 19:44 UTC, nkarunarathne commented
Looks good

2023-07-27 21:10 UTC, jamesaimonetti commented on src/seq/seq_getstream.erl
> +    cleanup(),
Each seq_* should cleanup after itself after running successfully. No need for double cleanup here

2023-07-27 21:11 UTC, jamesaimonetti commented on src/seq/seq_getstream.erl
> +    API = pqc_cb_api:init_api(['crossbar'], ['cb_websites']),
Have you actually run this test? You start cb_websites here but API calls lower down go to `cb_getstream`

2023-07-28 13:57 UTC, Navoda626 commented on src/seq/seq_getstream.erl
> +    cleanup(),
Got it. Thanks. Will remove the initial cleanup()

2023-07-28 13:58 UTC, Navoda626 commented on src/seq/seq_getstream.erl
> +    API = pqc_cb_api:init_api(['crossbar'], ['cb_websites']),
Yes test ran successfully locally, but now wonder how that happened.
Will change this to cb_getstream

2023-07-31 22:30 UTC, jamesaimonetti requested changes

2023-07-31 22:30 UTC, jamesaimonetti commented on src/seq/seq_getstream.erl
> +    cleanup(),
Extra `cleanup()` isn't necessary; if `F` runs successfully, all is cleaned up before the rest of `Fs` are run. If F crashes, no cleanup needed as we need the system unchanged to inspect where the failure occurred.
`cleanup/0` is called after a test failure to reset everything before running `seq` tests again.

2023-08-02 15:47 UTC, Navoda626 commented on src/seq/seq_getstream.erl
> +    cleanup(),
Got it! Thank you James! I will remove the extra `cleanup/0` function

2023-08-15 16:43 UTC, sanjeevie6353 commented on src/seq/seq_getstream.erl
> +    cleanup(),
This has been fixed.

2023-08-15 16:45 UTC, sanjeevie6353 commented on src/seq/seq_getstream.erl
> +    cleanup(),
This has been fixed.

2023-08-17 18:03 UTC, merged