KCRO-29: updating pqc_registrations to query kamailio for registrations
2600hz/kazoo-proper pull request #23
Opened 2020-11-04 19:07 UTC by icehess

In https://github.com/2600hz/kazoo-crossbar/pull/63 we switched to query regs
from kamailio.

Change the test here to ask kamailio if it available to get registrations

### Required/Related PRs
Updating view to return sip username from: 2600hz/kazoo-core#115

### Circular Required  PRs
https://github.com/2600hz/kazoo-crossbar/pull/63

2020-11-04 21:46 UTC, jamesaimonetti commented
@icehess instead of disabling, perhaps a check on kamailio's existence? Similar to https://github.com/2600hz/kazoo-properly/blob/master/src/pqc_sip_client.erl#L75

2020-11-10 18:29 UTC, jamesaimonetti requested changes

2020-11-10 18:29 UTC, jamesaimonetti commented on src/pqc_cb_registrations.erl
> +    %% DISABLING FOR NOW: with KCRO-29 (in kazoo-crossbar) we switched to query regs from kamailio, disabiling this until we
Would prefer to toggle this based on Kamailio existing in kz_nodes status.

2020-11-10 19:09 UTC, icehess commented on src/pqc_cb_registrations.erl
> +    %% DISABLING FOR NOW: with KCRO-29 (in kazoo-crossbar) we switched to query regs from kamailio, disabiling this until we
yup, I did the change, but didn't have time to test it locally with/without kamailio yet

2020-11-13 23:23 UTC, merged